language: java
dist: trusty
jdk: openjdk11
sudo: required
cache:
  directories:
    - $HOME/.m2
install:
- mvn --version
addons:
  apt:
    packages:
    - intltool
    - libgsf-1-dev
    - uuid-runtime
    - libglib2.0-dev
    - libxml2-dev
    - pdftk
notifications:
  slack: debrief-devs:GF1nQSqn2eozH3wQtyuPLAlG
before_script:
- export DISPLAY=:99
- sh -e /etc/init.d/xvfb start
- sleep 3
# modify Debrief feature to include win-64 subdirectory
- echo "root.win32.win32.x86_64 = win-64" >> org.mwc.debrief.combined.feature/build.properties
# get a 64-bit windows JRE
- wget -P dest https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jre_x64_windows_hotspot_11.0.5_10.zip
# unpack it
- cd dest
- tar xf OpenJD*.zip
# rename and move it
- mv *-jre jre
- mkdir ../org.mwc.debrief.combined.feature/win-64
- mv jre ../org.mwc.debrief.combined.feature/win-64/jre
# move it to the target folder
script: mvn clean verify -U -B -fae
after_failure:
- ls org.mwc.debrief.ui_test
- ls org.mwc.debrief.ui_test/target
- zip -r org.mwc.debrief.ui_test/target/results.zip org.mwc.debrief.ui_test/target/results
- curl -u ianmayo:chunkchunk -T org.mwc.debrief.ui_test/target/results.zip chunk.io
before_deploy:
- ls /home/travis/build/debrief/debrief/org.mwc.debrief.product/target/products/
- ./install-msitools.sh
- ./contribs/msi/make_x64msi.sh
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: KCCJkP6ELz9pIGkBmSRbazRzhKZPq7T58tEIZbthtVv+KoM/JWdN10h3IK/N5Oqdeb2/P5u+93ml1wlU9PkbuwxQ4mpUbaAW41G/9mbEF7U2JLEtS9xSxeIfEBIEtuHxdlECjsgMCLm2lh3CVxbu3S2y9jDnpt35rbh6AN3B44w=
  file:
    - /home/travis/build/debrief/debrief/org.mwc.debrief.product/target/products/DebriefNG-Linux64Bit.zip
    - /home/travis/build/debrief/debrief/org.mwc.debrief.product/target/products/DebriefNG-MacOSX64Bit.zip
    - /home/travis/build/debrief/debrief/org.mwc.debrief.product/target/products/DebriefNG-Windows32Bit.zip
    - /home/travis/build/debrief/debrief/org.mwc.debrief.product/target/products/DebriefNG-Windows64Bit.zip
    - /home/travis/build/debrief/debrief/org.mwc.debrief.product/target/products/P2_Repository.zip
    - /home/travis/build/debrief/debrief/org.mwc.debrief.legacy/dist/DebriefLegacy*.jar
    - /home/travis/build/debrief/debrief/org.mwc.debrief.lite/dist/debrief-lite*.zip
    - /home/travis/build/debrief/debrief/org.mwc.debrief.product/target/products/DebriefNG-Windows64Bit.msi
  on:
     tags: true
     all_branches: true
